name: demo_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  easy_localization: ^3.0.3
  connectivity: ^3.0.6
  settings_ui: ^2.0.0
  auto_size_text: ^3.0.0
  rxdart: ^0.27.0
  flutter_rating_bar: ^4.0.1
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  http: ^1.1.0
  flutter_svg: ^0.22.0
  like_button: ^2.0.5
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  dio_http_formatter: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/LoginPage/

